url: "https://mytory.net"
title: "웹으로 말하기"
author: "안형우"
description: >
  웹개발, PHP, CSS, jQuery, javascript,
  아이폰 등등
timezone: "Asia/Seoul"
paginate: 10
paginate_path: "page/:num"

email: "mail@mytory.net"
twitter_username: "mytory"
github_username: "mytory"

gems:
  - jekyll-paginate
  - jekyll-sitemap